### PR TITLE
Fix exp errors and improve log message formats

### PR DESCRIPTION
**Pull request by aontas**
This also adds current totals to update messages to give more context to the player.

Ideally this fixes the following issue:

image

And gives current level progress when levelling up.

### CODE REVIEW

**Comment by aontas** [comment]
Updated logs: 
image

image

**Comment by aontas** [comment]
Updates have fixed:
- Changes "experience points" to "XP" to shorten the log message (so that it fits on one line)
- Fixed XP to next level counting down (ie, remaining XP) rather than count up

**Comment by aontas** [comment]
Additional changes:
- Fixes HunterHunted fatal error (faction on spawned units now set correctly)
- Adds more logging on config loading
- Fixes XP calculation and displays current XP after death
- Hides bloodline internal logging by default (as this is mostly just trace level logging)

**Comment by Darkon47** [comment]
I have been torn on this because i misunderstood what you meant about the xp display change... after a detailed look this should be fine to merge.

**Pull request merged**
